url: www.opentechschool.org
baseurl: /
blog_domain: blog.opentechschool.org
css_version: 6
markdown: kramdown

encoding: UTF-8
exclude: ['scripts', 'sass', 'config.rb', 'Gemfile', 'Gemfile.lock', 'vendor']

