url: www.opentechschool.org
baseurl: /
blog_domain: blog.opentechschool.org
css_version: 4

encoding: UTF-8
exlude: ['scripts', 'sass', 'config.rb', 'Gemfile', 'Gemfile.lock']

members:
  Dortmund:
    - name: Carsten
      email: carsten@opentechschool.org
      img: carsten.jpg
    - name: Hendrik
      email: hendrik@opentechschool.org
      img: hendrik.jpg
    - name: Leif
      email: leif@opentechschool.org
      img: leif.jpg
    - name: Ola
      email: ola@opentechschool.org
      img: ola.jpg
  Melbourne:
    - name: Steven Farlie
      email: steven@opentechschool.org
      img: steven.jpg
    - name: Matthew Iversen
      email: matthew@opentechschool.org
      img: matthew.jpg
    - name: Angus Gratton
      email: angus@opentechschool.org
      img: angus.jpg
    - name: Lilly Ryan
      email: lilly@opentechschool.org
      img: lilly.jpg
  Nairobi:
    - name: Martha Chumo
      email: martha@opentechschool.org
      img: martha.jpg
    - name: Shiko Kimani
      email: shiko@opentechschool.org
      img: shiko.jpg
    - name: Timothy
      email: timothy@opentechschool.org
      img: timothy.jpg
